// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVfOlhqe5w58NKUdHk7Hc1Ua847BSHRvA',
    appId: '1:589682458153:web:c2097105ded7d8c162a638',
    messagingSenderId: '589682458153',
    projectId: 'olx-flutter-832dd',
    authDomain: 'olx-flutter-832dd.firebaseapp.com',
    storageBucket: 'olx-flutter-832dd.firebasestorage.app',
    measurementId: 'G-5K1FG3T3QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlazORbqECxRd5byBd6TqW4Ra-79ZcNQ0',
    appId: '1:589682458153:android:c618225babe29e3262a638',
    messagingSenderId: '589682458153',
    projectId: 'olx-flutter-832dd',
    storageBucket: 'olx-flutter-832dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmxAQCy-2W6Aye3ey2jgxFk-aU53qZneU',
    appId: '1:589682458153:ios:a99044e1e90e04ee62a638',
    messagingSenderId: '589682458153',
    projectId: 'olx-flutter-832dd',
    storageBucket: 'olx-flutter-832dd.firebasestorage.app',
    iosBundleId: 'com.example.olxFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmxAQCy-2W6Aye3ey2jgxFk-aU53qZneU',
    appId: '1:589682458153:ios:a99044e1e90e04ee62a638',
    messagingSenderId: '589682458153',
    projectId: 'olx-flutter-832dd',
    storageBucket: 'olx-flutter-832dd.firebasestorage.app',
    iosBundleId: 'com.example.olxFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVfOlhqe5w58NKUdHk7Hc1Ua847BSHRvA',
    appId: '1:589682458153:web:739d3385596b253b62a638',
    messagingSenderId: '589682458153',
    projectId: 'olx-flutter-832dd',
    authDomain: 'olx-flutter-832dd.firebaseapp.com',
    storageBucket: 'olx-flutter-832dd.firebasestorage.app',
    measurementId: 'G-NW5W89ZBG0',
  );
}
